### ISSUE TITLE
Not compatible with recent solana_rbpf version

### ISSUE THREAD

**Issue by leqiang-deltafi** [acheroncrypto/solana-deployer#2]
@spacemandev-git 
When running `Cargo build --release`, the dependency solana_rbpf will be installed with version 0.2.31, and the code here is out-dated to the recent version:
https://github.com/acheroncrypto/solana-deployer/blob/890e386e694df7cc8b9c0fac6505d2c6746827a4/src/main.rs#L345-L353
there is not check function anymore, from_elf function only accept 3 parameters, and there should be another bool flag for register_syscalls

**Comment by acheroncrypto** [comment]
Thanks for the report, added a commit with fixed versioning.
